scriptSigningKey: "MAKE SURE YOU CHANGE THIS IN PRODUCTION"
auth: # TODO remove
  httpsOnly: false
  proxied: false
# telegram:
#   botToken: YOU
#   chatId: REALLYWANTTHIS
exchanges:
  simulated:
    apiKey: DEMO
  gdax:
    apiKey:
    secretKey:
    passphrase:
    sandbox: false # default
    loadRemoteData: true # default. Disable if the exchange goes down to avoid spamming it for metadata requests
  binance:
    apiKey:
    secretKey:
    loadRemoteData: true
  kucoin:
    apiKey:
    secretKey:
    passphrase:
    sandbox: false
    loadRemoteData: true
  bitfinex:
    apiKey:
    secretKey:
    loadRemoteData: true
  bitmex:
    apiKey:
    secretKey:
    loadRemoteData: true
  kraken:
    apiKey:
    secretKey:
    loadRemoteData: true
  bittrex:
    apiKey:
    secretKey:
    loadRemoteData:
jerseyClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  connectionRequestTimeout: 5000ms
server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  connector:
    type: http
    port: 8081
  maxThreads: 16
logging:
  loggers:
    "com.gruelbox.orko": INFO
    "com.gruelbox.orko.app.exchangebroker": INFO
    "si.mazi.rescu": ERROR
producer:
  type: basic
  bootstrapServers:
    - localhost:9092
  name: marketdata
  keySerializer:
    type: string
  valueSerializer:
    type: string
  acks: all
  retries: 2147483647 # int max value
  maxInFlightRequestsPerConnection: 1
  maxPollBlockTime: 10s
consumer: 
  type: basic
  bootstrapServers:
    - localhost:9092
  consumerGroupId: marketdata
  name: marketdata  
  keyDeserializer:
    type: string
  valueDeserializer:
    type: string