version: "3"
services:
  db:
    image: mongo
    networks:
      - webnet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jsmith
      - MONGO_INITDB_ROOT_PASSWORD=some-initial-password
      - MONGO_INITDB_DATABASE=oco
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    image: llcoolg/oco-web:0.0.1-SNAPSHOT
    networks:
      - webnet
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    image: llcoolg/oco-worker:0.0.1-SNAPSHOT
    networks:
      - webnet
  ui:
    build:
      context: ./oco-ui
    image: llcoolg/oco-ui:latest
    ports:
      - '80:80'
    networks:
      - webnet
networks:
  webnet: