loopSeconds: 10
auth:
  userName: bully
  password: boy
  proxied: false
  whitelistExpirySeconds: 7200
database:
  mongoClientURI: mongodb://jsmith:some-initial-password@db:27017
  mongoDatabase: oco
  lockSeconds: 30
mq:
  clientURI: amqp://mq
server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080
jerseyClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  connectionRequestTimeout: 5000ms
#logging:
#  level: TRACE