loopSeconds: ${LOOP_SECONDS:-3}
auth:
  userName: ${USER_NAME}
  password: ${PASSWORD}
  secretKey: ${AUTH_TOKEN}
  proxied: ${PROXIED}
database:
  mongoClientURI: ${MONGODB_URI}
  mongoDatabase: ${MONGO_DATABASE}
  lockSeconds: ${LOCK_SECONDS:-10}
telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
  chatId: ${TELEGRAM_CHAT_ID}
exchanges:
  gdax-sandbox:
    apiKey: ${GDAX_SANDBOX_API_KEY}
    secretKey: ${GDAX_SANDBOX_SECRET}
    passphrase: ${GDAX_SANDBOX_PASSPHRASE}
  gdax:
    apiKey: ${GDAX_API_KEY}
    secretKey: ${GDAX_SECRET}
    passphrase: ${GDAX_PASSPHRASE}
  binance:
    apiKey: ${BINANCE_API_KEY}
    secretKey: ${BINANCE_SECRET}
  kucoin:
    apiKey: ${KUCOIN_API_KEY}
    secretKey: ${KUCOIN_SECRET}
server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080
jerseyClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  connectionRequestTimeout: 5000ms
#logging:
#  level: TRACE