loopSeconds: ${LOOP_SECONDS:-3}
lockSeconds: ${LOCK_SECONDS:-10}
userName: ${USER_NAME}
password: ${PASSWORD}
mongoClientURI: ${MONGODB_URI}
mongoDatabase: ${MONGO_DATABASE}
telegram:
  botToken: ${TELEGRAM_BOT_TOKEN}
  chatId: ${TELEGRAM_CHAT_ID}
server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080
jerseyClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  connectionRequestTimeout: 5000ms
#logging:
#  level: TRACE