version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          MAVEN_OPTS: -Xmx3200m
    working_directory: ~/orko
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v2-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v2-{{ .Branch }}-
            - maven-repo-v2-
      - restore_cache:
          keys:
            - node-v2-{{ .Branch }}-{{ checksum "orko-ui/package-lock.json" }}
            - node-v2-{{ .Branch }}-
            - node-v2-
      - run: mvn -Pproduction clean install -DskipTests=true
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - /usr/local/lib/node_modules
            - orko-ui/node_modules
          key: node-v2-{{ .Branch }}-{{ checksum "orko-ui/package-lock.json" }}
      - persist_to_workspace:
          root: ~/orko
          paths:
            - orko-common
            - orko-all-in-one
            - orko-end-to-end-testing
            - start-integration-test.sh
  integration-test:
    docker:
      - image: cypress/base:10
    parallelism: 1
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - cypress-v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run: cd orko-end-to-end-testing && npm ci
      - run: ./start-integration-test.sh &
      - run: cd orko-end-to-end-testing && wait-on http://localhost:8080
      - run: cd orko-end-to-end-testing && npx cypress verify
      - save_cache:
          key: cypress-v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - .cache/Cypress
      - attach_workspace:
          at: ~/
      - run:
          name: Run Cypress tests
          command: "cd orko-end-to-end-testing && npx cypress run"
workflows:
  version: 2
  all:
    jobs:
      - build
      - integration-test:
          requires:
            - build
