version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
          environment:
            MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - orko-build-{{ checksum "pom.xml" }}
      - run: mvn de.qaware.maven:go-offline-maven-plugin:1.0.0:resolve-dependencies -Dmaven.repo.local=.m2/repository
      - save_cache:
          paths:
            - ~/.m2
          key: orko-build-{{ checksum "pom.xml" }}
      - run: mvn -Pproduction clean package -T 1C -DskipSlowTests=true
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit  
  mysql:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          MAVEN_OPTS: -Xmx3200m
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test
          MYSQL_USER: open
          MYSQL_PASSWORD: sesame
    steps:
      - checkout
      - restore_cache:
          keys:
            - orko-build-{{ checksum "pom.xml" }}
      - run: mvn de.qaware.maven:go-offline-maven-plugin:1.0.0:resolve-dependencies -Dmaven.repo.local=.m2/repository
      - save_cache:
          paths:
            - ~/.m2
          key: orko-build-{{ checksum "pom.xml" }}
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: mvn -Pwebdev clean package -T 1C -DskipSlowTests=true -Dtestdb.url=mysql://open:sesame@127.0.0.1/test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit  
workflows:
  version: 2
  all:
    jobs:
      - build
      - mysql
