version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          MAVEN_OPTS: -Xmx3200m
    working_directory: ~/orko
    steps:
      - run: sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

      - checkout

      - restore_cache:
          keys:
            - maven-repo-v2-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v2-{{ .Branch }}-
            - maven-repo-v2-
      - restore_cache:
          keys:
            - node-v3-{{ .Branch }}-{{ checksum "orko-ui/package-lock.json" }}
            - node-v3-{{ .Branch }}-
            - node-v3-
      - restore_cache:
          keys:
            - cypress-v1-{{ .Branch }}-{{ checksum "orko-end-to-end-testing/package.json" }}

      - run: mvn -Pintegration-test clean install -DskipSlowTests=true -T 1C

      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - /usr/local/lib/node_modules
            - orko-ui/node_modules
            - orko-ui/node
          key: node-v3-{{ .Branch }}-{{ checksum "orko-ui/package-lock.json" }}
      - run:
          name: Saving checkstyle reports
          command: |
            mkdir -p ~/checkstyle/
            find . -type f -regex ".*/target/checkstyle-result.xml" -exec cp {} ~/checkstyle \;
          when: always
      - store_artifacts:
          path: ~/checkstyle
      - run:
          name: Saving test results (H2)
          command: |
            mkdir -p ~/junit/h2
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/h2 \;
          when: always
      - store_artifacts:
          path: ~/junit
      - store_test_results:
          path: ~/junit

      - save_cache:
          key: cypress-v1-{{ .Branch }}-{{ checksum "orko-end-to-end-testing/package.json" }}
          paths:
            - orko-end-to-end-testing/node_modules
            - orko-end-to-end-testing/node
            - ~/.npm
            - ~/.cache
      - store_artifacts:
          path: orko-end-to-end-testing/screenshots
      - store_artifacts:
          path: orko-end-to-end-testing/app.log
      - store_artifacts:
          path: orko-end-to-end-testing/videos
workflows:
  version: 2
  all:
    jobs:
      - build
