version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
        environment:
          MAVEN_OPTS: -Xmx3200m
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test
          MYSQL_USER: open
          MYSQL_PASSWORD: sesame
    working_directory: ~/orko
    steps:
      - run: sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

      - checkout

      - restore_cache:
          keys:
            - maven-repo-v2-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v2-{{ .Branch }}-
            - maven-repo-v2-
      - restore_cache:
          keys:
            - node-v3-{{ .Branch }}-{{ checksum "orko-ui/package-lock.json" }}
            - node-v3-{{ .Branch }}-
            - node-v3-
      - restore_cache:
          keys:
            - cypress-v2-{{ .Branch }}-{{ checksum "orko-end-to-end-testing/package.json" }}

      - run: mvn -Pintegration-test clean install -DskipSlowTests=true -T 1C

      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - /usr/local/lib/node_modules
            - orko-ui/node_modules
            - orko-ui/node
          key: node-v3-{{ .Branch }}-{{ checksum "orko-ui/package-lock.json" }}
      - save_cache:
          key: cypress-v2-{{ .Branch }}-{{ checksum "orko-end-to-end-testing/package.json" }}
          paths:
            - orko-end-to-end-testing/node_modules
            - orko-end-to-end-testing/node
            - ~/.npm
            - ~/.cache

      - run:
          name: Saving checkstyle reports
          command: |
            mkdir -p ~/checkstyle/
            find . -type f -regex ".*/target/checkstyle-result.xml" -exec cp {} ~/checkstyle \;
          when: always
      - store_artifacts:
          path: ~/checkstyle

      - run:
          name: Saving test results (H2)
          command: |
            mkdir -p ~/junit/h2
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/h2 \;
          when: always

      - run:
          name: Saving test results (Integration)
          command: |
            mkdir -p ~/junit/integration
            find . -type f -regex ".*/target/mocha-reports/.*xml" -exec cp {} ~/junit/integration \;
          when: always

      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: mvn -Pwebdev surefire:test -Dmorf.mysql.noadmin=true -DskipSlowTests=true -Dtestdb.url=mysql://open:sesame@127.0.0.1/test

      - run:
          name: Saving test results (MySQL)
          command: |
            mkdir -p ~/junit/mysql
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/mysql \;
          when: always

      - store_artifacts:
          path: ~/junit
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: orko-end-to-end-testing/cypress/screenshots
      - store_artifacts:
          path: orko-end-to-end-testing/app.log
workflows:
  version: 2
  all:
    jobs:
      - build
