version: 2
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/d1538bdca20be1aa31d8
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers@sha256:40ae64c13a503125a452cb5ffb5c01d14742c01d3676d77aa276fc6b956168be
        environment:
          MAVEN_OPTS: -Xmx3200m
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test
          MYSQL_USER: open
          MYSQL_PASSWORD: sesame  
    working_directory: ~/orko
    steps:
      - run: sudo apt-get install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

      - checkout

      - restore_cache:
          keys:
            - maven-repo-v2-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v2-{{ .Branch }}-
            - maven-repo-v2-
      - restore_cache:
          keys:
            - node-v4-{{ .Branch }}-{{ checksum "orko-ui/package-lock.json" }}-{{ checksum "orko-end-to-end-testing/package-lock.json" }}
            - node-v4-{{ .Branch }}-
            - node-v4-

      - run:
          command: |
            echo "Branch: $CIRCLE_BRANCH"
            echo "Project: $CIRCLE_REPOSITORY_URL"
            echo " - Username: $CIRCLE_PROJECT_USERNAME"
            echo " - Repository: $CIRCLE_PROJECT_REPONAME"
            echo "Pull request: $CIRCLE_PULL_REQUEST"
            echo " - Username: $CIRCLE_PR_USERNAME"
            echo " - Repository: $CIRCLE_PR_REPONAME"
            if [[ $CIRCLE_PROJECT_USERNAME == "gruelbox" ]]; then
              mvn -B -U -Pintegration-test clean install -DskipSlowTests=true -Dskip.surefire.tests=true -Dskip.failsafe.tests=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dcypress.command=runrecord -T 1C
            else
              mvn -B -U -Pintegration-test clean install -DskipSlowTests=true -Dskip.surefire.tests=true -Dskip.failsafe.tests=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -T 1C
            fi

      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v4-{{ .Branch }}-{{ checksum "orko-ui/package-lock.json" }}}-{{ checksum "orko-end-to-end-testing/package-lock.json" }}

      - run:
          name: Saving checkstyle reports
          command: |
            mkdir -p ~/checkstyle/
            find . -type f -regex ".*/target/checkstyle-result.xml" -exec cp {} ~/checkstyle \;
          when: always
      - store_artifacts:
          path: ~/checkstyle

      - run:
          name: Saving test results (H2)
          command: |
            mkdir -p ~/junit/h2
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/h2 \;
          when: always

      - run:
          name: Saving test results (end-to-end)
          command: |
            mkdir -p ~/junit/end-to-end
            find . -type f -regex ".*/target/mocha-reports/.*xml" -exec cp {} ~/junit/end-to-end \;
          when: always
          
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 30`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
            
      - run:
          name: Running tests on MySQL
          command: mvn -B -U surefire:test -Dmorf.mysql.noadmin=true -DskipSlowTests=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dtestdb.url=mysql://open:sesame@127.0.0.1/test

      - run:
          name: Saving test results (MySQL)
          command: |
            mkdir -p ~/junit/mysql
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/mysql \;
          when: always
          

      - store_artifacts:
          path: ~/junit
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: orko-end-to-end-testing/cypress/screenshots
      - store_artifacts:
          path: orko-end-to-end-testing/app.log
workflows:
  version: 2
  all:
    jobs:
      - build
