loopSeconds: 3
auth:
  httpsOnly: false
  proxied: false
#  ipWhitelisting:
#    whitelistExpirySeconds: 86400
#    secretKey: YOURTOKEN
#  jwt:
#    userName: joe
#    password: bloggs
#    secret: CHANGEME
#    secondFactorSecret: YOURTOKEN
#    expirationMinutes: 1440
#  okta:
#    baseUrl: SEE
#    issuer: THE
#    clientId: README
database:
  connectionString: h2:file:./orko;DB_CLOSE_DELAY=-1;MVCC=TRUE;DEFAULT_LOCK_TIMEOUT=60000
# telegram:
#   botToken: YOU
#   chatId: REALLYWANTTHIS
exchanges:
  gdax-sandbox:
    apiKey: 
    secretKey: 
    passphrase: 
  gdax:
    apiKey: 
    secretKey: 
    passphrase: 
  binance:
    apiKey: 
    secretKey:
  kucoin:
    apiKey: 
    secretKey: 
  cryptopia:
    apiKey: 
    secretKey: 
  bitfinex:
    apiKey: 
    secretKey: 
jerseyClient:
  timeout: 5000ms
  connectionTimeout: 5000ms
  connectionRequestTimeout: 5000ms
server:
  type: simple
  rootPath: /api/
  applicationContextPath: /
  connector:
    type: http
    port: 8080
  maxThreads: 16
logging:
  loggers:
    "com.grahamcrockford.orko": INFO
    "si.mazi.rescu": ERROR