version: 1

update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/orko-ui"
    update_schedule: "live"

  - package_manager: "javascript"
    directory: "/orko-end-to-end-testing"
    update_schedule: "live"
